[주다희] 장바구니 추가 기능
wecode-bootcamp-korea/29-1st-KIKEA-backend pull request #12
Opened 2022-01-31 16:05 UTC by newdana01

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니에 상품을 추가할 수 있다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
상품을 장바구니에 담을 수 있다.
이미 존재하는 상품 옵션인 경우 수량만 업데이트 한다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 장바구니 상품 추가 기능을 구현할 수 있다.

<br />

## :: 기타 질문 및 특이 사항
-

2022-02-07 05:01 UTC, shawn365 commented on orders/views.py
> +            product_option = ProductOption.objects.get(id=product_option_id)
code convention 확인해주세요 :)

2022-02-07 08:17 UTC, bigfanoftim requested changes

2022-02-07 08:17 UTC, bigfanoftim commented on orders/views.py
> +from users.utils     import @login_decorator
```suggestion
from users.utils     import login_decorator
```

2022-02-07 08:17 UTC, bigfanoftim commented on orders/views.py
> +            quantity = 1
```suggestion
            data = json.loads(request.body)
            quantity = data['quantity]
```

2022-02-07 08:17 UTC, bigfanoftim commented on orders/views.py
> +                    user           = User.objects.get(id=request.user.id),
```suggestion
                    user           = request.user,
```

2022-02-07 11:58 UTC, newdana01 commented on orders/views.py
> +            quantity = 1
수정하였습니다😸

2022-02-07 11:58 UTC, newdana01 commented on orders/views.py
> +                    user           = User.objects.get(id=request.user.id),
수정하였습니다😸

2022-02-07 11:59 UTC, newdana01 commented on orders/views.py
> +from users.utils     import @login_decorator
수정하였습니다

2022-02-08 01:41 UTC, bigfanoftim approved these changes
LGTM 👍

2022-02-08 01:41 UTC, merged