[장바구니 ] 장바구니 조회 기능 구현
wecode-bootcamp-korea/29-1st-KIKEA-backend pull request #13
Opened 2022-01-31 16:15 UTC by newdana01

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니에 담아둔 상품을 조회할 수 있다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 장바구니에 담긴 상품을 조회할 수 있다.
- 색상 및 사이즈 옵션이 없을 경우 해당 값은 'NULL'로 처리한다.
- 장바구니에 상품이 담겨있지 않을 경우 'NO_PRODUCT' 메세지를 반환한다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- DB상으로 foreign key 값이 null이어서 테이블 참조 시 Nonetype을 참조하게 되는 경우 이를 처리할 수 있는 방법에 대해 알게 되었습니다.
-  foreign key 값을 이용한 정참조에 대해서 한번 더 개념을 잡을 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-02-05 15:46 UTC, shawn365 reviewed
list comprehension 적용하면 더 좋을거 같아요

2022-02-07 08:27 UTC, bigfanoftim requested changes

2022-02-07 08:27 UTC, bigfanoftim commented on orders/views.py
> +        carts   = Cart.objects.filter(user=user_id)
```suggestion
        carts   = Cart.objects.filter(user=request.user)
```

2022-02-07 08:27 UTC, bigfanoftim commented on orders/views.py
> +            )
```suggestion
            result.append(
                {
                    'product_option_id'   : cart.product_option.id,
                    'name'                : cart.product_option.product.name,
                    'type'                : cart.product_option.product.type.name,
                    'color'               : cart.product_option.color.name if cart.product_option.color else None,
                    'size'                : size,
                    'quantity'            : cart.quantity,
                    'price'               : cart.product_option.price,
                    'total_price'         : cart.quantity * cart.product_option.price,
                    'default_image'       : cart.product_option.product.default_image
                }
            )
```

2022-02-07 12:25 UTC, newdana01 commented on orders/views.py
> +        carts   = Cart.objects.filter(user=user_id)
수정했습니다 ^__^

2022-02-07 12:49 UTC, newdana01 commented on orders/views.py
> +            )
수정했습니다 ^__^

2022-02-08 01:42 UTC, bigfanoftim requested changes

2022-02-08 01:42 UTC, bigfanoftim commented on orders/views.py
> +        carts   = Cart.objects.filter(user=1)
하드 코딩 수정해주세요

2022-02-08 02:08 UTC, newdana01 commented on orders/views.py
> +        carts   = Cart.objects.filter(user=1)
수정했습니다 !!

2022-02-08 06:55 UTC, bigfanoftim reviewed
LGTM 👍

2022-02-08 06:56 UTC, merged