[김성수] 유저 로그인 기능 구현
wecode-bootcamp-korea/29-1st-KIKEA-backend pull request #18
Opened 2022-02-05 15:45 UTC by shawn365

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 이메일이 있는지 확인후 없으면 에러 메세지 반환
- 이메일이 있고 이메일과 비밀번호가 맞을시 성공 메세지 그외엔 실패 메세지 반환

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항

2022-02-07 02:36 UTC, newdana01 reviewed
LGTM 👍

2022-02-07 08:33 UTC, bigfanoftim requested changes

2022-02-07 08:33 UTC, bigfanoftim commented on users/views.py
> +from my_settings            import SECRET_KEY, ALGORITHM
```suggestion
from django.conf            import settings
# settings.SECRET_KEY
```

2022-02-08 01:43 UTC, bigfanoftim approved these changes
LGTM 👍

2022-02-08 01:44 UTC, merged