[김성수] 로그인 데코레이터 구현
wecode-bootcamp-korea/29-1st-KIKEA-backend pull request #19
Opened 2022-02-05 15:56 UTC by shawn365

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
로그인 데코레이터 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 토큰을 받아와 틀리면 에러메세지 반환
- 유저가 없을시 에러메세지 반환
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-02-07 02:37 UTC, newdana01 reviewed
LGTM 👍

2022-02-07 08:34 UTC, bigfanoftim requested changes

2022-02-07 08:34 UTC, bigfanoftim commented on users/utils.py
> +            request.user = user
```suggestion
            request.user         = User.objects.get(id=payload['user_id'])   

```

2022-02-08 01:44 UTC, bigfanoftim approved these changes
LGTM 👍

2022-02-08 01:44 UTC, merged